### PR TITLE
Draft cmake integration

### LINKED ISSUE #268: infrastructure: Use CMake instead of the current build system
The current build system, with included Makefiles from 6 folders up in the directory tree seems to me like reinventing the wheel. We should consider using a more standardised build system, like CMake, ninja or the like

### PR DESCRIPTION
**Pull request by cristian-vijelie**
Currently, only the binaries in `app-interact` are built with `cmake`.
To build, run

```
.../operating-systems/content$ mkdir build/ && cd build/
.../operating-systems/content/build$ cmake -S .. -B .
.../operating-systems/content/build$ make -j $(nproc)
```

All executables will be built in the `build/` folder, following a structure similar to the source files locations.

For example, the executable generated from `content/chapters/app-interact/lab/support/password-cracker/password-cracker-multiprocess.c` will be located in `content/build/chapters/app-interact/lab/support/password-cracker/`

Closes #268

### CODE REVIEW

**Comment by gabrielmocanu** [comment]
@cristian-vijelie  Any reason to close it?

**Comment by cristian-vijelie** [comment]
@gabrielmocanu close what?

**Comment by gabrielmocanu** [comment]
image
I see, you deleted your fork.

**Comment by cristian-vijelie** [comment]
Fk.

**Pull request closed without merging**
