### PR TITLE
app-interact/lab: Rename so-cloud section to os-cloud

### LINKED ISSUE #140: app-interact/lab: Rename the `so-cloud` section to `os-cloud`
This requires changes to the [`config.yaml` file](https://github.com/open-education-hub/operating-systems/blob/master/config.yaml#L217), to the [Markdown content](https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/SO%20Cloud/content/so-cloud), the [Arena](https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/Arena/content/arena#so-cloud-more-disk-customization) and renaming the [exercise's directory](https://github.com/open-education-hub/operating-systems/tree/master/content/chapters/app-interact/lab/support/so-cloud).

### PR DESCRIPTION
**Pull request by RaresCroicia**
Change [`config.yaml`](https://github.com/open-education-hub/operating-systems/blob/master/config.yaml#L217), the Markdown content of [`SO-cloud`](https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/SO%20Cloud/content/so-cloud) and [`Arena`](https://open-education-hub.github.io/operating-systems/Lab/Application-Interaction/Arena/content/arena#so-cloud-more-disk-customization) to show **os-cloud** instead of **so-cloud**, also rename the exercise's directory as well as the docker container and change some details into the files in order to match with the content of the exercise.

Fixes #140. 

Signed-off-by: RaresCroicia <rarescroicia@gmail.com>

### CODE REVIEW

**Comment by Alex-deVis** [comment]
Hi, @RaresCroicia, please also include a fix for the linter errors. `gitleaks` complains about a private key being part of a commit.

```
2023-02-12 20:00:00 [ERROR]   Found errors in [gitleaks] linter!
2023-02-12 20:00:00 [ERROR]   Error code: 1. Command output:
------

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

Finding:     -----BEGIN OPENSSH PRIVATE KEY-----   
```

This can be solved by creating a `.gitleaks.toml` and adding `/os-cloud/keys` folder to the `[allowlist]`. Find more information on this here [1].

**Comment by RaresCroicia** [comment]
I added the `.gitleaks.toml` file, but it seems it doesn't work. Did I do something wrong? @Alex-deVis

**Review by teodutu — CHANGES_REQUESTED** [review]
This looks OK. I haven't tested it yet, but you forgot to remove the files below and replace their occurrences:

```sh
teo@lautari operating-systems $ rg files/
content/chapters/app-interact/lab/solution/os-cloud/disk-templates/ubuntu_22.04/copy_files.sh
36:cp files/99-so-cloud-welcome "$disk_mnt_dir/etc/update-motd.d"

content/chapters/app-interact/lab/support/os-cloud/disk-templates/ubuntu_22.04/copy_files.sh
36:cp files/99-so-cloud-welcome "$disk_mnt_dir/etc/update-motd.d"
```

**Comment by RaresCroicia** [comment]
Changed what you requested, also I found other places I missed replacing, but I have a question. In `keys/ssh_key.pub`, in both `support/` and `solution/`, there is the user called **so-cloud-user**, should I change those too?

```sh
❯ rg -i 'so-cloud'
content/chapters/app-interact/lab/solution/os-cloud/keys/ssh_key.pub
1:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8CDHgeE4NIIIih3wSz58GDkfPLUk2m9gmbZB1f6o8Lzawzb3HVFpslAUWK0f/Ymw9cloInpMo50gWMYFSyJ7ZrOWWak54BedpHDkFAxxy+JCE9b+pkKsrAT7wiir7gn2LHlhj55FLZkC9PpM9cBcrMfzlcP9Bf+2cnpDdINybSLmOUmrI23ANteM4lEVaa2yEbCaJk6dFB8+atz5zPjvVI0Hd+kJK7yJ0xV6Zc2ADle7TKW3dyiXOE9qFKe9933Rj7ocqNXCAO1cxUoJCVuVS7lh+1pSSPXLWLTOhVp/XiLGWVP6KRYmmn710MWKm9Kj1tPiGUphUraL20SJiRT6/ so-cloud-user

content/chapters/app-interact/lab/support/os-cloud/keys/ssh_key.pub
1:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8CDHgeE4NIIIih3wSz58GDkfPLUk2m9gmbZB1f6o8Lzawzb3HVFpslAUWK0f/Ymw9cloInpMo50gWMYFSyJ7ZrOWWak54BedpHDkFAxxy+JCE9b+pkKsrAT7wiir7gn2LHlhj55FLZkC9PpM9cBcrMfzlcP9Bf+2cnpDdINybSLmOUmrI23ANteM4lEVaa2yEbCaJk6dFB8+atz5zPjvVI0Hd+kJK7yJ0xV6Zc2ADle7TKW3dyiXOE9qFKe9933Rj7ocqNXCAO1cxUoJCVuVS7lh+1pSSPXLWLTOhVp/XiLGWVP6KRYmmn710MWKm9Kj1tPiGUphUraL20SJiRT6/ so-cloud-user
```

**Review by teodutu — CHANGES_REQUESTED** [review]
Good catch @RaresCroicia. Yes, change the keys as well. I tested this and it seems to work fine. Apart from the keys, what you need to do now is to

- remove the `app-interact/lab/support/so-cloud` folder altogether
- update "SO-Cloud" from [this image](https://github.com/open-education-hub/operating-systems/blob/master/content/chapters/app-interact/lab/media/so_cloud.svg) to "OS-Cloud". While you're doing this, please also add a white background to it (add a white rectangle behind the image like [this image](https://github.com/open-education-hub/operating-systems/blob/master/content/chapters/compute/lecture/media/app-process-thread.svg)). To edit `.svg` files, upload them [to this website](https://app.diagrams.net/) where you can modify them. After you've changed the image, click `File -> Export As -> SVG` and then check "Embed fonts".

@molecula2788 please also take a look at this.

**Comment by RaresCroicia** [comment]
Modified the user on the keys and also added the white background to the `os-cloud.svg` and renamed + changed the occurrences to match the new name in the markdown files. 

> remove the `app-interact/lab/support/so-cloud` folder altogether

When you say this, are you referring to `app-interact/lab/support/os-cloud`? Because `support/so-cloud/` doesn't exist anymore and I got confused of the request.

**Comment by molecula2788** [comment]
> @molecula2788 please also take a look at this.

Looks okay to me.

**Review by teodutu — APPROVED** [review]
> When you say this, are you referring to app-interact/lab/support/os-cloud? Because support/so-cloud/ doesn't exist anymore and I got confused because of your request, so took no action towards it yet.

Yes, you're right. That directory was left over on my system. This looks right.

**Pull request merged**
