### PR TITLE
workflows: Configure and disable Markdown linter options

### PR DESCRIPTION
**Pull request by Alex-deVis**
* Disable **MD004** to allow use of both `+` and `-` in lists mainly for quizzes
* Configure **MD035** to allow the use of `----`
* Disable **MD041** to allow files to start without a top-level header

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
This is great! Please also disable `MD004` so we can start list items with both `+` and `-` in quizzes.

**Comment by Alex-deVis** [comment]
> This is great! Please also disable MD004 so we can start list items with both + and - in quizzes.

Done. We could also use [in-line comments to update rules](https://github.com/DavidAnson/markdownlint#configuration) to avoid updating the global configuration

**Comment by razvand** [comment]
@Alex-deVis , @teodutu ,  I don't understand all the specifics of the Markdown linting. But if it works, then I'm all up for it. How did you test it?

**Comment by Alex-deVis** [comment]
I am using `markdownlint` as a vscode extension. It reports problems in real-time and keeps its rules in a json file.

**Comment by teodutu** [comment]
Same as @Alex-deVis: I'm using the VSCode extension. I didn't know `config.json` also works for `markdownlint` as a Github action. Also, @Alex-deVis add the reason for disabling `MD004` in the commit description so in the future it's clear why we got rid of it.

**Review by teodutu — APPROVED** [review]
:+1:

**Review by razvand — CHANGES_REQUESTED** [review]
@Alex-deVis , please ensure an empty blank line between the first line of the commit and the rest.

Modify the first line to `workflows: Configure and disable Markdown linter options` (DON'T end with dot - `.`).

Use present tense for all sentences, for consistency: `Disable`, `Configure`, `Disable`.

**Review by razvand — APPROVED** [review]
Thanks, @Alex-deVis

**Pull request merged**
