### PR TITLE
Software Stack lab - Fix image link

### PR DESCRIPTION
**Pull request by RazvanN7**
cc @Alex-deVis @teodutu

### CODE REVIEW

**Comment by RazvanN7** [comment]
Can't we put the builder as a tester so that such things do not happen anymore?

**Review by Alex-deVis — APPROVED** [review]

**Comment by teodutu** [comment]
> Can't we put the builder as a tester so that such things do not happen anymore?

https://github.com/open-education-hub/operating-systems/issues/102

**Review by teodutu — APPROVED** [review]
:+1: When you merge this, update the commit message to `software-stack/lab: ...`.

**Comment by RazvanN7** [comment]
ah damn.

**Pull request merged**
