### PR TITLE
compute/lecture: Update unikraft demo

### PR DESCRIPTION
**Pull request by StefanJum**
This commit updates the unikraft demo for cooperative scheduling by:

- **Removing dependencies on the `kraft` cli tool (since it has been deprecated)**
- Merging all functionalities in one script
- Updating `main.c` to use pthreads function for better readability

To use the script, use:
```console
$ ./do.sh setup
$ ./do.sh build
$ ./do.sh run_nocoop
$ ./do.sh run_coop
```

### CODE REVIEW

**Comment by StefanJum** [comment]
> Please update the Compute slides as well (26.2 shows an example on how to run the script).

Done @lizababu, also changed the script to build both apps once, at the same time, and have separate run commands.

**Review by lizababu — APPROVED** [review]
LGTM! Thanks for the update.

**Comment by elena19m** [comment]
I think you should also add installing `qemu-system-x86_64` as part of the setup.

**Comment by StefanJum** [comment]
> I think you should also add installing `qemu-system-x86_64` as part of the setup.

You're right @elena19m, done.

**Comment by StefanJum** [comment]
Fixed the linter errors

**Review by teodutu — APPROVED** [review]
The `markdownlint` error is a pre-existing problem. I think we can ignore it for this PR. We're waiting for @razvand's old ass (as usual).

**Pull request merged**
