### PR TITLE
util/super-linter: Add interactive option

### PR DESCRIPTION
**Pull request by Alex-deVis**
Add "-i" flag to start the super-linter container in interactive mode, with bash as entrypoint.

### CODE REVIEW

**Comment by teodutu** [comment]
You haven't explained why this is needed. What improvements does it bring?

**Comment by Alex-deVis** [comment]
> What improvements does it bring?

You can use the interactive mode to update a linter config file and see the results in real time.
You can also use this for debugging - I misplaced the `CPPLINT.cfg` file and needed to enter the container to realize it.

**Review by teodutu — APPROVED** [review]
Makes sense I guess.

**Comment by gabrielmocanu** [comment]
I want to test it first.

**Comment by gabrielmocanu** [comment]
Ok. Good job!

**Review by gabrielmocanu — APPROVED** [review]

**Pull request merged**
