### PR TITLE
assignments/mini-libc: Use `errno` in implementation of `write()` and `read()`

### LINKED ISSUE #232: `assignments/mini-libc`: Use `errno` in implementation of `write()` and `read()`
The implementation of `write()` and `read()` in the [implementation in `libc/`](https://github.com/open-education-hub/operating-systems/blob/master/content/assignments/mini-libc/libc/io/read_write.c) does not set `errno`. `errno` should be set according to the manual pages of [`write`](https://man7.org/linux/man-pages/man2/write.2.html) and [`read`](https://man7.org/linux/man-pages/man2/read.2.html).

### PR DESCRIPTION
**Pull request by teodorjuravlea**
Fixes #232

### CODE REVIEW

**Comment by teodorjuravlea** [comment]
> > `checkpatch.pl` is yelling at you for good reason. Fix the coding style.
> 
> Nvm, you've already done that heart.

Working on it right now. :D

**Comment by teodorjuravlea** [comment]
Anything wrong with the commit description? I see checkpatch doesn't like it.

**Comment by teodutu** [comment]
> Anything wrong with the commit description? I see checkpatch doesn't like it.

Yes. Your commit only has a title. Between that and the signature, there should be a description of why the commit is necessary, what problem it solves etc. You can draw inspiration from the issue's text.

**Comment by teodutu** [comment]
> Is this good?

I think so. We'll see what @razvand has to say as well

**Comment by gabrielmocanu** [comment]
@razvand  bump on this.

**Review by razvand — APPROVED** [review]
This works.

**Pull request merged**
