### PR TITLE
data: Fix typo in working-memory.md

### PR DESCRIPTION
**Pull request by MekalBoy**
Updated comment to reflect actual content in code.

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
Thanks for the fix! What you need to do to make the checkpatch test pass [1] is to add the following line to your commit message:

```
Signed-off-by: <Your Name> <your email>
```

To do so, configure your user name and email like so:
```
git config --global user.name "Your Name"
git config --global user.email "your email"
```
After this, add your email to GitHub so it doesn't appear as "23715925+MekalBoy@users.noreply.github.com"

Then run `git commit --amend -s` to add the signed-off line automatically to your last commit. Finally, use `git push -f` to replace your existing upstream commit with the one you've just amended. Don't worry about the spellcheck failure. It's just about some words that are unknown to the linter.

[1] https://github.com/open-education-hub/operating-systems/actions/runs/6590761580/job/17908015178?pr=339#step:3:570

**Comment by MekalBoy** [comment]
Turns out I had to update my settings and add another GPG key that has my other email, otherwise it wouldn't sign.

**Comment by teodutu** [comment]
The checkpatch error seems to persist. It seems you haven't set your name and email on GitHub as in the signature. Try doing this and then update the commit without changes (`git commit --amend --no-edit`) and re-push it (`git push -f`).

**Review by teodutu — APPROVED** [review]
Yup, now it's working. Don't worry about the spellcheck failure. Its dictionary is not rich enough yet.

**Pull request merged**
