### PR TITLE
Add clang-format action

### PR DESCRIPTION
**Pull request by Alex-deVis**
This will run `clang-format --dry-run --Werror` using `.clang-format` file from the repository root.
Reported errors can be automatically resolved using `clang-format -i <files>`.

Closes https://github.com/open-education-hub/operating-systems/issues/170.

### CODE REVIEW

**Comment by Alex-deVis** [comment]
The `.clang-format` file is only a draft. @teodutu, you are the one concerned with spaces instead of tabs, can you improve it?

**Review by teodutu — APPROVED** [review]
I made tabs mandatory and changed their width to 8 spaces. The rest looks OK so far

**Review by teodutu — COMMENTED** [review]
The errors output by `clang-format` are really inexpressive. They only say "error: code should be clang-formatted [-Wclang-format-violations]".

**Comment by Alex-deVis** [comment]
8 spaces seem like a lot. If you opt for this, also update the max line length: `ColumnLimit: 120`.

**Comment by Alex-deVis** [comment]
@razvand, @gabrielmocanu, please provide your input. I will merge this later today and we can come back to it in another PR.

**Comment by teodutu** [comment]
image
:cry:

**Review by teodutu — CHANGES_REQUESTED** [review]
Many of these changes make no sense, like `main() {` instead of:
```
main()
{
```
I think you should tone down `clang-format` a bit.

**Comment by Alex-deVis** [comment]
The files are not to be manually checked. We decide what rules we want and format all sources.
I am fine with the way it formats, but I think it would be best if you use it on a codebase you know and see what changes.

**Comment by teodutu** [comment]
Honestly, we already have `checkpatch.pl` [1]. Isn't that enough? I saw it wasn't working when it should have, though. I think we should investigate that instead of adding a new linter, which by default contradicts our main coding style (that of the Linux kernel).

[1] https://github.com/open-education-hub/operating-systems/blob/master/.github/workflows/checkpatch.yml

**Comment by razvand** [comment]
@Alex-deVis, make this go away.

We had, at one point, `clang-format` support in PR #15. And then we disabled it in PR #24, due to its lack of configurability and pedantry. As @teodutu pointed out, `checkpatch.pl` is good. And we can integrate `cppcheck` (see issue #26), that's a more humane linter.

**Comment by Alex-deVis** [comment]
The statement about `clang-format` not being configurable from https://github.com/open-education-hub/operating-systems/issues/24 is not right (see `.clang-format` file).

I understand though the need for a more humane linter, therefore I will create a PR to configure `checkpatch.pl` and close this one.

**Pull request closed without merging**
