### PR TITLE
{lab,lecture}: Add license to sol and support files

### PR DESCRIPTION
**Pull request by mariasfiraiala**
As stated in #87, some files are missing a license. This PR adds the `SPDX-License-Identifier: BSD-3-Clause` to all support and solution files from all labs. It covers `py`, `c`, `cpp`, `d`, `java`, `S`, `s`, `asm` and header files.

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

### CODE REVIEW

**Review by teodutu — CHANGES_REQUESTED** [review]
The work you've done so far is good, except for the `.d` files. There are 4 things to consider:
1. The D language suggests single-line comments use `//` instead of `/* */`, so please update them accordingly.
2. You should add license comments to lecture demos as well. It would be a shame not to fix all the code now that you have started doing it.
3. Apart from the lecture code, there are still some lab files without license comments:
```console
teo@obor operating-systems-oer $ find content/chapters/*/lab -regextype egrep -regex '.*\.(py|c|d)' | xargs grep -L SPDX
[...]
content/chapters/io/lab/support/async/python/async_server.py
content/chapters/io/lab/support/async/python/async_server_3.6.py
content/chapters/software-stack/lab/solution/common-functions/printf.c
content/chapters/software-stack/lab/solution/common-functions/string.c
content/chapters/software-stack/lab/support/common-functions/printf.c
content/chapters/software-stack/lab/support/common-functions/string.c
content/chapters/software-stack/lab/support/high-level-lang/hello.py
content/chapters/software-stack/lab/support/static-dynamic/hello.c
content/chapters/software-stack/lab/support/syscall-wrapper/main.c
```
I trimmed out the first lines of this output, as they were open-source code or spurious loggers.
4. Your changes have introduced some linter errors, such as [1]. You need to fix them before we can merge this. There are also a few errors such as [2] which I have been unable to fix or rather ignore before. It would be great if you could, but it's not mandatory.

[1] https://github.com/open-education-hub/operating-systems/actions/runs/3832235293/jobs/6522313189#step:4:3732
[2] https://github.com/open-education-hub/operating-systems/actions/runs/3832235293/jobs/6522313189#step:4:2128

**Comment by mariasfiraiala** [comment]
Thanks @teodutu. I've changed the license for `d` files and added the license to lecture files as well as missing lab ones, except for  `content/chapters/software-stack/lab/solution/common-functions/printf.c` and `content/chapters/software-stack/lab/support/common-functions/printf.c`, which already have one.

As for the linter error introduced by this PR that you've linked, I don't really understand what is the issue it finds.

Please take another look when you've got the time!

**Comment by teodutu** [comment]
@mariasfiraiala the error I was referring to [1] says that you should have left an additional empty line after the license comment in `app-interact/lab/solution/so-cloud/so-cloud/errors.py`.

And now, luckily for us and a little less so fo you, since you've made changes to nearly all code files, the linter has revealed coding style errors in multiple files. They're mostly cosmetic, such as missing / extra white spaces, so please fix them as well.

[1] https://github.com/open-education-hub/operating-systems/actions/runs/3846675116/jobs/6552250772#step:4:5644

**Comment by mariasfiraiala** [comment]
@teodutu I've modified the files and hopefully managed to solve some linter errors, even though I've chosen to ignore some of them as they were quite nonsensical to me. Point out the ones that you feel that require my attention again.

**Comment by mariasfiraiala** [comment]
@teodutu I took a look at the files that are mentioned regarding using `snprintf` instead of `strcpy` and `sprintf`. I don't feel like we should replace these calls with `snprintf` for a couple of reasons:

1. It doesn't help with readability, on the contrary; for copying one string to another, people are already familiarized with `strcpy` doing the job and `snprintf` brings a layer of abstraction (and 2 more arguments to the function call) that confuses the reader.

1. Some files use `strcpy` for demonstration purposes (one example is `content/chapters/software-stack/lab/support/common-functions/string.c`, where we are supposed to find implementations for both `strlen` and `strcpy` as part of the lab observation)

1. One lecture demo (`content/chapters/data/lecture/demo/security/nts.c`) uses `strcpy` exactly because it is not safe.

For these reasons, and because, generally, the course is not focused on security no matter what, I feel like we shouldn't jump on using `snprintf`. What do you think?

**Comment by teodutu** [comment]
>     1. It doesn't help with readability, on the contrary; for copying one string to another, people are already familiarized with `strcpy` doing the job and `snprintf` brings a layer of abstraction (and 2 more arguments to the function call) that confuses the reader.

I'll get back to you about this one.

>     2. Some files use `strcpy` for demonstration purposes (one example is `content/chapters/software-stack/lab/support/common-functions/string.c`, where we are supposed to find implementations for both `strlen` and `strcpy` as part of the lab observation)
> 
>     3. One lecture demo (`content/chapters/data/lecture/demo/security/nts.c`) uses `strcpy` exactly because it is not safe.

You're definitely right about 2 and 3. To silence these errors, add a `CPPLINT.cfg` file that removes the `runtime/printf` filter to the directories you mentioned. Use the [global `CPPLINT.cfg`](https://github.com/open-education-hub/operating-systems/blob/master/content/CPPLINT.cfg) as a model.

**Comment by mariasfiraiala** [comment]
@teodutu I've added the `CPPLINT.cfg` files to all concerned directories. All that's left now are 3 files that use `strcpy`.

**Comment by mariasfiraiala** [comment]
Regarding actually preparing students security wise (which is probably why you're suggesting adding `snprintf`), the [memory-security section](https://open-education-hub.github.io/operating-systems/Lab/Data/Memory%20Security/content/memory-security) from the data lab should introduce this function and properly explain its usage. To the already existing skel, just add:

* index out of bounds

* integer overflow

* string formatting

and you have the perfect intro to vulnerabilities and defense mechanisms.

**Review by teodutu — CHANGES_REQUESTED** [review]
I think `strcpy()` should be fine as it is globally. So to wrap this up, remove the `runtime/printf` filter from [the global `CPPLINT.cfg`](https://github.com/open-education-hub/operating-systems/blob/master/content/CPPLINT.cfg) and then you can remove the local `CPPLINT.cfg`s you've added. Sorry for being inconsistent. When this is done, the PR can be merged.

**Comment by mariasfiraiala** [comment]
@teodutu Done, thanks for your patience.

**Review by teodutu — APPROVED** [review]
It's over, at last :peace_symbol:.

**Pull request merged**
