### PR TITLE
Permit use of `volatile' qualifier in checkpatch

### PR DESCRIPTION
**Pull request by Traian-Enache**

### CODE REVIEW

**Comment by gabrielmocanu** [comment]
@Traian-Enache 

Do this issue occurs on a specific PR?

**Comment by teodutu** [comment]
@Traian-Enache, as @gabrielmocanu said, first provide more details about why this argument is needed.

**Comment by gabrielmocanu** [comment]
@Traian-Enache  bump on this

**Comment by gabrielmocanu** [comment]
@Traian-Enache  bump again

**Comment by razvand** [comment]
@Traian-Enache , @gabrielmocanu , @teodutu , closing this due to lack of activity.

**Pull request closed without merging**
